---
title: '**STOR 320.1: Intro to Data Science**'
geometry: margin=2
output:
  prettydoc::html_pretty:
    theme: cayman
  pdf_document:
    toc: yes
---

<style type="text/css">

div {
color: #13294B;
}

#TOC {
  color: #4B9CD3;
}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
  color: #4B9CD3;
  background-color: #13294B;
}

a:link {
    color: #4B9CD3;
    text-decoration: none;
}

a:visited {
        text-decoration: none;
color: #4B9CD3;

}
a:hover {
color: #4B9CD3;
background-color: #13294B;
}

.main-container {
  max-width: 300px;
  margin-left: auto;
  margin-right: auto;
}

.column {
  float: left;
  width: 50%;
}

.row:after {
  content: "";
  display: table;
  clear: both;
} 

</style>

# **About the Course**

See the **[syllabus](https://hannig.cloudapps.unc.edu//STOR320/Syllabus.pdf)** for details. The course is divided into three rough parts,

1. Core data science coding skills
2. Modeling
3. Advanced topics

- Instructor: **[Jan Hannig](https://hannig.cloudapps.unc.edu)**

- Instructional Assistants: 
    - **[Taylor Petty](http://stat-or.unc.edu/people/graduate-students-department)**
    - **[Pavlos Zoubouglou](http://stat-or.unc.edu/people/graduate-students-department)**
    - **[Sam Booth](http://stat-or.unc.edu/people/graduate-students-department)**

- Lab Sections: 
    - 320.400 by Taylor: W 5:45 PM to 6:35 PM
    - 320.401 by Pavlos: W 4:40 PM to 5:30 PM
    - 320.402 by Sam:    F 4:40 PM to 5:30 PM


- Zoom Links:
    - **[Lectures:](https://unc.zoom.us/j/94535557682?pwd=YWEwYzVWN0VSNHB1QnZHUTR1T2pkZz09)** TTH 2:00 PM to 3:15 PM
    - **[320.400 by Taylor](https://unc.zoom.us/j/91440986085?pwd=WUpKeW5hVG0rNGRXaXlZZStJL2xuUT09)**: W 5:45 PM to 6:35 PM
    - **[320.401 by Pavlos](https://unc.zoom.us/j/93735742250)**: W 4:40 PM to 5:30 PM
    - **[320.402 by Sam](https://unc.zoom.us/j/5891075192)**: F 4:40 PM to 5:30 PM
    - **[Instructor Office Hours:](https://unc.zoom.us/j/91787829144?pwd= bFQwUW9HUG85d2VaZkZvRVBFV1g wdz09)** MW 2:00 PM to 3:00 PM
    - **[Taylor Office Hours:](https://unc.zoom.us/j/91440986085?pwd=WUpKeW5hVG0rNGRXaXlZZStJL2xuUT09)** M 10:00 AM to 11:00 AM and W 1:30 PM to 2:30 PM
    - **[Pavlos Office Hours:](https://unc.zoom.us/j/2903979720)** M 10:00 AM to 11:00 AM and F 1:00 PM to 2:00 PM
    - **[Sam Office Hours:](https://unc.zoom.us/j/5891075192)** TuTh 4:00 PM to 5:00 PM


# **Course Material**

| Date | Lecture | Slides | Tutorial|
|------|---------|--------:|--------:|
|Jan. 19| Welcome/Data Visualization | [Slides](Lecture/STOR320_01.pdf)| [Tutorial 01](Tutorial/Tutorial01.Rmd)|
|Jan. 21| RMarkdown |[Slides](Lecture/STOR320_02.pdf) | [Tutorial 02](Tutorial/Tutorial02.Rmd) [ (Final Plot)](Tutorial/finalplot.png) [ {Solution}](Tutorial/Tutorial02_sol.Rmd)|
|Jan 26| Data Transformation I|[Slides](Lecture/STOR320_03.pdf) | [Tutorial 03](Tutorial/Tutorial03.Rmd) [ {Solution}](Tutorial/Tutorial03_sol.Rmd)|
|Jan 28| Data Transformation II |[Slides](Lecture/STOR320_04.pdf) | |
|Feb 2| Data Transformation III | [Slides](Lecture/STOR320_05.pdf)| [Tutorial 04](Tutorial/Tutorial04.zip) [ {Solution}](Tutorial/Tutorial04_sol.Rmd)|
|Feb 4| Final Project Instructions|[Slides](Lecture/STOR320_06.pdf) | |
|Feb 9| Data Import |[Slides](Lecture/STOR320_07.pdf) | |
|Feb 11| Exploratory Data Analysis |[Slides](Lecture/STOR320_08.pdf) | |
|Feb 16| Wellness Day | | |
|Feb 18| CLASS CANCELLED - ice storm | | |
|Feb 23| Project Proposal Discussion | | |
|Feb 25| Tidy Data |[Slides](Lecture/STOR320_09.pdf) | [Tutorial 05](Tutorial/Tutorial05.Rmd) |
|Mar 2| Web Scraping |[Slides](Lecture/STOR320_10.pdf) | [Tutorial 06](Tutorial/Tutorial06.Rmd) |
|Mar 4| Joins |[Slides](Lecture/STOR320_11.pdf)  | [Tutorial 07](Tutorial/Tutorial07.Rmd) |
|Mar 9| Factors |[Slides](Lecture/STOR320_12.pdf) | |
|Mar 11| Wellness Day | | |
|Mar 16| Programming I |[Slides](Lecture/STOR320_13.pdf) |[Tutorial 08](Tutorial/Tutorial08.Rmd) |
|Mar 18| Programming II|[Slides](Lecture/STOR320_14.pdf) |[Tutorial 09](Tutorial/Tutorial09.Rmd) |
|Mar 23| Programming III |[Slides](Lecture/STOR320_15.pdf) | |
|Mar 25| Modeling I |[Slides](Lecture/STOR320_16.pdf) | |
|Mar 30| Group Work Day || |
|Apr 1| Modeling II |[Slides](Lecture/STOR320_17.pdf) |[Tutorial 10](Tutorial/Tutorial10.zip)  |
|Apr 6| Modeling III |[Slides](Lecture/STOR320_18.pdf) |[Tutorial 11](Tutorial/Tutorial11.zip) |
|Apr 8| Modeling IV |[Slides](Lecture/STOR320_19.pdf)  | |
|Apr 13| Modeling V |[Slides](Lecture/STOR320_20.pdf)  | |
|Apr 15| Modeling VI |[Slides](Lecture/STOR320_21.pdf)  | [Tutorial 12](Tutorial/Tutorial12.Rmd) |
|Apr 20| Modeling VII |[Slides](Lecture/STOR320_22.pdf)  |[Tutorial 13](Tutorial/Tutorial13.Rmd) |
|Apr 22| R Shiny|[Slides](Lecture/STOR320_23.pdf) | [Tutorial 14](Tutorial/Tutorial14.zip)|
|Apr 27| Data Ethics |[Slides](Lecture/STOR320_24.pdf) | |
|Apr 29| Presentation| | |
|May 4| Presentation|| | |

# **Homework Tracker**

All homework assignments are to be submitted via **[Gradescope](https://sakai.unc.edu/portal/site/stor320.001.sp21)**. 

| Date assigned | Instructions | Solutions| Due Date (Time) |
|----------|:--------:|:-------------:|----------------:|
| Jan 21  | [HW1](Homework/HW1.Rmd) | | Jan 28 |
| Jan 28  | [HW2](Homework/HW-2.Rmd) | | Feb 4 |
| Feb 4  | [A1](Homework/Analysis-1.zip) | | **Feb 21** |
| Feb 18  | [HW3](Homework/HW-3.Rmd) | |Feb 25 |
| Feb 25  | [HW4](Homework/HW-4.Rmd) | | Mar 4 |
| Mar 4  | [A2](Homework/Analysis-2.zip) | | Mar 18 |
| Mar 18  | [HW5](Homework/HW-5.Rmd) | | Mar 25 |
| Mar 23 | [A3](Homework/Analysis-3.zip)| | Apr 8 |
| Apr 9  | [HW6](Homework/HW-6.Rmd) | | Apr 15 |
| Apr 15  | [HW7](Homework/HW-7.Rmd) | |Apr 22 |
| Apr 22  | [A4](Homework/Analysis-4.zip) | | May 4|

# **Final Project Details**

For the final project, each section of STOR 320 will be divided (ideally) into research groups of size 5. To ensure fairness, students will be assigned randomly based on the `sample` function in **R**. 

## Research Group Assignments

To find your research group, see file `group.xlsx` in the **Resources** tab on **Sakai**.

## Four Roles

Although everyone is responsible for the entire project, each member of the group will be assigned a specific role for accountability and consistency. These four specific roles are described as follows:

- **The Creator:** Meet with Instructor to Propose Your Group's Research Idea, Lead Designer in Slides

- **The Interpreter:** Schedule and Meet with Instructor or Instructional Assistant to Share Findings from Exploratory Analysis, Evaluate Practice Presentation

- **The Orator(s):** Give a Captivating 5-7 Minute Slideshow Presentation During the Last Two Lectures

- **The Deliverer:** Deliver Your Group from Evil by Editing and Submitting the Exploratory Analysis and Final Report via Sakai Before the Deadline

## Four Parts Including Point Values

This final project will be divided into four parts worth a total of 100 points. Each part will have a clear rubric as non-subjective as possible. The parts along with total point values are found below:

* **[P1: Project Proposal](FinalProject/Project-Proposal.html)** *(10 Points)*
    + [Template](FinalProject/Project_Proposal_Template.Rmd)
    + [Data World](https://data.world/datasets/download)
    + [US Government Data](https://www.data.gov/)
    + [Kaggle](https://www.kaggle.com/)
    + [Free Data Info I](https://www.forbes.com/sites/bernardmarr/2016/02/12/big-data-35-brilliant-and-free-data-sources-for-2016/#63f06f60b54d)
    + [Free Data Info II](https://r-dir.com/reference/datasets.html)


* **[P2: Exploratory Data Analysis](FinalProject/Exploratory-Data-Analysis.html)** *(20 Points)*
    + [Template](FinalProject/EDA_Template.Rmd)
    
* **[P3: Final Written Paper](FinalProject/Final-Paper.html)** *(40 Points)*
    + [Template](FinalProject/Final_Report_Template.Rmd)
    + [Group Scoring]()
    
* **[P4: Final Presentation](FinalProject/Final-Presentation.html)** *(30 Points)*

    
## Due Dates of Individual Parts

| Part | Description |Method of Submission| Due Date (Time) |
|------|-------------|-------------------|----------------:|
| P1  | Project Proposal | Gradescope | **Feb 21**|
|   | Proposal Meeting | In class | **Feb 23**|
| P2  | Exploratory Data Analysis | Gradescope | April 6|
|   | EDA Meeting | In Lab | April 6-9|
| P3  | Final Report|Gradescope| May 5|
| P4  | Presentation Slides |Sakai| April 28|
|   | Final Presentation|In Class| April 29 and May 4|

## Above Average Final Projects from Previous Courses

- **[Pokemon](FinalProject/SP2019_EX1.html)**
- **[Seattle Housing](FinalProject/SP2019_EX2.html)**
- **[Missing Migrants](FinalProject/SU2019_EX1.html)**
- **[Youtube](FinalProject/FA2019_EX1.html)**
- **[CDC](FinalProject/FA2019_EX2.html)**

# **Acknowledgements**

Thanks to Dr. Mario, Dr Li and Dr. Characiejus for sharing their course materials. 

# **Reading**

- **[R for Data Science](https://r4ds.had.co.nz/)** (R4DS)


- **[Text Mining with R](https://www.tidytextmining.com/)** (TMwR)


- **[ModernDive](https://moderndive.com/index.html)** (MD)

- **[R Programming for Data Science](https://drive.google.com/file/d/1XVF5v4MTBhIp_dq9MzTI0TtPfVrF6eaZ/view?usp=sharing)** (RP4DS)

- **[The Art of R Programming](https://drive.google.com/file/d/1gR7Yr9-pIZ-f315bZCXfDj9yPWaZDflD/view?usp=sharing)** (AoRP)

- **[A First Course in Statistical Programming with R](https://drive.google.com/file/d/1NBadpF5MLWI3AFsyWo3nbpQnL8sWeZdT/view?usp=sharing)** (FCSPR)

- **[An Introduction to Statistical Learning](https://drive.google.com/file/d/1jKxVWG89KvWr_-70sOeEeLK4CUB09sRu/view?usp=sharing)** (ISLR)


# **Additional resources**

- **[Installing R](https://cran.r-project.org/)**

- **[Installing R Studio](https://www.rstudio.com/products/rstudio/#Desktop)**

- **[Additional Necessary Tools for Mac Users](https://mac.r-project.org/tools/)**

- **[Instructions for Accessing R Studio on the UNC Server](https://drive.google.com/file/d/1ATZO-wpuqzHbXVnJqm7wXpt-yfMbo2Jy/view?usp=sharing)**

- **[Rmarkdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)**

- **[ggplot2 Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)**

- **[Color Options](https://paulvanderlaken.files.wordpress.com/2017/08/ggplot2-color-colours-names-cheatsheet.png?w=559&amp;h=1024)**

- **[Data Wrangling Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)**

- **[R Shiny Cheat Sheet](https://shiny.rstudio.com/images/shiny-cheatsheet.pdf)**

- **[R Strings Cheat Sheet](https://evoldyn.gitlab.io/evomics-2018/ref-sheets/R_strings.pdf)**

This page was last updated on `r Sys.time()` Eastern Time.
